#' Cross-validation testing for DCPO
#'
#' \code{claassen_xvt} performs a single cross-validation test for Claassen's Model 5 estimates of cross-national public opinion
#'
#' @param dcpo_input a data frame of survey items and marginals generated by \code{DCPOtools::dcpo_setup}
#' @param fold_number an integer indicating the number of the fold to treated as test data in the current analysis
#' @param number_of_folds an integer indicating the total number of folds
#' @param fold_seed a seed for reproducably randomly assigning observations to folds; when a complete set of k-fold cross-validations is to be performed, the same seed should be used for all
#' @param chime play chime when complete?
#' @param ... arguments to be passed to \code{rstan::stan}. Defaults reset by \code{dcpo} are
#' described below under details.
#
#' @details \code{claassen_kfold} performs a single cross-validation test of Claassen's Model 5.  To perform
#' a complete k-fold cross-validation, call it repeatedly, changing only the fold_number argument.
#'
#' @examples
#' \dontrun{
#'
#' demsup <- read_csv(system.file("extdata", "all_data_demsupport.csv", package = "DCPOtools"))
#'
#' demsup_data <- format_claassen(demsup %>% with_min_yrs(3))
#'
#' # Single cross-validation test with 25% test set
#' claassen_demsup_xvtest <- claassen_xvt(demsup_data,
#'                            number_of_folds = 4)
#'
#' # k-fold cross-validation with 10 folds (claassen_demsup_kfold will be a list of stanfit objects)
#' claassen_demsup_kfold <- purrr::map(1:10, function(x) {
#'                               claassen_xvt(demsup_data,
#'                                          fold_number = x, # number_of_folds = 10 is the default
#'                                          iter = 150)
#'                                          })
#' }
#' @return a stanfit object
#'
#' @import rstan
#' @importFrom beepr beep
#' @importFrom dplyr group_by mutate ungroup arrange summarize_if select mutate_at vars contains first last nth filter
#' @importFrom forcats as_factor
#'
#' @export

claassen_xvt <- function(dcpo_input,
                       fold_number = 1,
                       number_of_folds = 10,
                       fold_seed = 324,
                       chime = TRUE,
                       ...) {

  set.seed(fold_seed)

  dat <- dcpo_input$data %>%
    group_by(country, year, item) %>%
    mutate(fold = runif(min = 1, max = number_of_folds, n = 1) %>% round()) %>%
    ungroup() %>%
    mutate(test = as.numeric(fold == fold_number)) %>%
    arrange(test, country, year, item) %>%
    mutate(jj = forcats::as_factor(country),
           tt = year - min(year) + 1,
           kk = forcats::as_factor(item),
           pp = as.numeric(as.factor(paste(country, item))))

  claassen_input_fold <- list(  N       = nrow(dat %>% filter(!test)),
                                J       = max(as.numeric(dat$jj)),
                                K       = max(as.numeric(dat$kk)),
                                T       = max(dat$tt),
                                P       = max(dat$pp),
                                jj      = as.numeric(dat %>% filter(!test) %>% pull(jj)),
                                kk      = as.numeric(dat %>% filter(!test) %>% pull(kk)),
                                tt      = dat %>% filter(!test) %>% pull(tt),
                                pp      = dat %>% filter(!test) %>% pull(pp),
                                x       = round(dat %>% filter(!test) %>% pull(x)),
                                samp    = round(dat %>% filter(!test) %>% pull(samp)),
                                N_test  = nrow(dat %>% filter(test==1)),
                                jj_test = as.numeric(dat %>% filter(test==1) %>% pull(jj)),
                                kk_test = as.numeric(dat %>% filter(test==1) %>% pull(kk)),
                                tt_test = dat %>% filter(test==1) %>% pull(tt),
                                pp_test = dat %>% filter(test==1) %>% pull(pp),
                                samp_test = round(dat %>% filter(test==1) %>% pull(samp)),
                                data    = dat)

  claassen_model <- stan_model(file = here::here("R", "claassen_xvt.stan"))
  stan_args <- list(object = claassen_model,
                    data = claassen_input_fold,
                    ...)
  if (!length(stan_args$control)) {
    stan_args$control <- list(adapt_delta = 0.99, stepsize = 0.005, max_treedepth = 14)
  }
  if (!length(stan_args$seed)) {
    stan_args$seed <- 324
  }
  if (!length(stan_args$thin)) {
    stan_args$thin <- 2
  }
  if (!length(stan_args$pars)) {
    stan_args$pars <- "x_test"
  }
  if (!length(stan_args$cores)) {
    stan_args$cores <- min(stan_args$chains, parallel::detectCores()/2)
  }
  claassen_output_fold <- do.call(rstan::sampling, stan_args)

  # Chime
  if(chime) {
    try(beep())
  }

  out1 <- list(claassen_input_fold = claassen_input_fold,
               claassen_output_fold = claassen_output_fold,
               xvt_args = list(fold_number = fold_number, number_of_folds = number_of_folds, fold_seed = fold_seed))
  return(out1)
}

#' @export
get_claassen_xvt_results <- function(claassen_xvt_output, ci = 80) {
  kfc <- assess_claassen_kfold_convergence(claassen_xvt_output = claassen_xvt_output)
  if (nrow(kfc) > 0) {
    cat("These estimates have not yet fully converged. Increase the number of iterations.\n")
    print(kfc)
  }

 if (length(names(claassen_xvt_output)[3]) > 0) {
   xvt_results <- c_xvt(claassen_xvt_output = claassen_xvt_output, ci = ci)
 } else {
   xvt_results <- purrr::map_df(claassen_xvt_output, function(x) {
     c_xvt(claassen_xvt_output = x, ci = ci)
     })

   mean_results <- xvt_results %>%
     mutate(country_means = (model == "country means")) %>%
     group_by(country_means) %>%
     summarize_if(is.numeric, mean) %>%
     mutate(model = c("k-fold mean", "mean country means")) %>%
     ungroup() %>%
     select(-country_means) %>%
     mutate(mae = round(mae, 3),
            improv_over_cmmae = round(improv_over_cmmae, 1)) %>%
     mutate_at(vars(contains("coverage")), round, 1)

   xvt_results <- xvt_results %>%
     bind_rows(mean_results)
 }
  return(xvt_results)
}

c_xvt <- function(claassen_xvt_output = claassen_xvt_output, ci = ci) {
  test_data <- claassen_xvt_output %>%
    dplyr::first() %>%
    dplyr::last() %>%
    dplyr::filter(test == 1)

  x_test_all <- claassen_xvt_output %>%
    dplyr::nth(2) %>%
    rstan::extract(pars = "x_test") %>%
    dplyr::first()

  model_mae <- mean(abs(test_data$x/test_data$samp - (colMeans(x_test_all)/test_data$samp))) %>%
    round(3)

  country_mean <- test_data %>%
    dplyr::group_by(country) %>%
    dplyr::mutate(country_mean = mean(x/samp)) %>%
    dplyr::ungroup()
  country_mean_mae <- mean(abs((country_mean$x/country_mean$samp - country_mean$country_mean))) %>%
    round(3)

  improv_vs_cmmae <- round((country_mean_mae - model_mae)/country_mean_mae * 100, 1)


  coverage <- (mean(test_data$x >= apply(x_test_all, 2, quantile, (1-ci/100)/2) &
                      test_data$x <= apply(x_test_all, 2, quantile, 1-(1-ci/100)/2)) * 100) %>%
    round(1)

  xvt_results <- tibble::tibble(model = c(paste0("Fold ", claassen_xvt_output$xvt_args$fold_number, " of ", claassen_xvt_output$xvt_args$number_of_folds, " (", claassen_xvt_output$xvt_args$fold_seed,")"), "country means"),
                                mae = c(model_mae, country_mean_mae),
                                improv_over_cmmae = c(improv_vs_cmmae, NA))
  ci_name <- paste0("coverage", ci, "ci")
  xvt_results[[ci_name]] <- c(coverage, NA)

  return(xvt_results)
}

assess_claassen_kfold_convergence <- function(claassen_xvt_output) {
  if (length(names(claassen_xvt_output)[3]) > 0) {
    kfc <- claassen_xvt_output %>%
      dplyr::nth(2) %>%
      summary() %>%
      `[[`("summary") %>%
      as.data.frame() %>%
      tibble::rownames_to_column(var = "parameter") %>%
      mutate(fold = claassen_xvt_output$xvt_args$fold_number) %>%
      filter(Rhat > 1.1) %>%
      select(parameter, mean, se_mean, sd, `2.5%`, `50%`, `97.5%`, n_eff, Rhat, fold)
  } else {
    kfc <- claassen_xvt_output %>%
      purrr::map_df(function(x) {
        x %>%
          dplyr::nth(2) %>%
          summary() %>%
          `[[`("summary") %>%
          as.data.frame() %>%
          tibble::rownames_to_column(var = "parameter") %>%
          mutate(fold = x$xvt_args$fold_number) %>%
          filter(Rhat > 1.1) %>%
          select(parameter, mean, se_mean, sd, `2.5%`, `50%`, `97.5%`, n_eff, Rhat, fold)
      })
  }
  return(kfc)
}
